### ISSUE TITLE
cant be cloned

### ISSUE THREAD

**Issue by khoneketa** [WHMCS/sample-registrar-module#5]
Cloning into 'sample-registrar-module'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by WHMCSPeter** [comment]
Hello,

Apologies for the delay in response.

This issue occurs because you are trying to clone using SSH without a public key registered against your GitHub account.

Instead, you may wish to try cloning using the HTTPS method, which does not require authentication:

```
git clone https://github.com/WHMCS/sample-registrar-module.git
```
